"""One write, traced from a browser tab, by the same code a lesson would use.

This is not a demo written specially for the harness. It is the shortest real thing a lesson does,
and it is here so that the page proves the whole stack rather than proving that a kernel boots.
Between the first line and the last it goes Python in a worker, a blocking call across a shared
buffer, JavaScript on the page, a busybox shell on a serial line, the tracer inside the guest, and
all the way back with the answer parsed and drawn.

If any one of those is broken this raises, and it raises where the break is rather than showing an
empty picture. That is worth more on this page than a friendly error, because the only person
running it is somebody trying to find out whether it works.

It hands back JSON, because the caller is JavaScript. The one interesting field is `html`, which is
the same widget markup a notebook would show, generated by the same `kxwidgets` code.
"""

import json
import os

from kxbox.bridge import V86
from kxwidgets import SyscallTape

# Which build of the kernel is behind the bridge. It changes nothing about what runs here, and it
# is asked for because a tape that does not say which kernel it came off is a tape nobody can
# check. The page sets it from the query string before this runs.
box = V86.find(profile=os.environ.get("KXBOX_PROFILE", "A-full"))
if box is None:
    raise RuntimeError(
        "there is no `kxbox` object on the worker's global scope, so Python came up but the "
        "bridge to the emulator did not"
    )

# Filtered to `vfs_write` alone. Unfiltered, a single write on this kernel is a few thousand lines,
# and the point being made is that a real trace arrives, not that a lot of it arrives.
tape = box.tape(
    "vfs-write",
    do=lambda: box.write("/tmp/one-byte", "x"),
    functions=("vfs_write",),
)

widget = SyscallTape(tape, max_depth=3, title="One write, traced in a browser tab")

json.dumps(
    {
        "kernel": box.read("/proc/version").strip(),
        "backend": box.describe(),
        "frames": tape.frame_count,
        "roots": [root.name for root in tape.roots][:5],
        "root_count": len(tape.roots),
        "unparsed": len(tape.unparsed),
        "html": widget.html(),
        "text": widget.text(),
    }
)
