"""One page fault, traced from a browser tab, by the same code a lesson would use.

This is not a demo written specially for the harness. It is the shortest real thing a lesson does,
and it is here so that the page proves the whole stack rather than proving that a kernel boots.
Between the first line and the last it goes Python in a worker, a blocking call across a shared
buffer, JavaScript on the page, a busybox shell on a serial line, the tracer inside the guest, and
all the way back with the answer parsed and drawn.

If any one of those is broken this raises, and it raises where the break is rather than showing an
empty picture. That is worth more on this page than a friendly error, because the only person
running it is somebody trying to find out whether it works.

It hands back JSON, because the caller is JavaScript. The one interesting field is `html`, which is
the same widget markup a notebook would show, generated by the same `kxwidgets` code.
"""

import json
import os

from kxbox.bridge import V86
from kxwidgets import SyscallTape

# Which build of the kernel is behind the bridge. It changes nothing about what runs here, and it
# is asked for because a tape that does not say which kernel it came off is a tape nobody can
# check. The page sets it from the query string before this runs.
box = V86.find(profile=os.environ.get("KXBOX_PROFILE", "A-full"))
if box is None:
    raise RuntimeError(
        "there is no `kxbox` object on the worker's global scope, so Python came up but the "
        "bridge to the emulator did not"
    )

# The `page-fault` recipe, run the way the recipe says to run it, rather than a trace of this
# page's own invention. `/bin/touchpage` opens the tracer window from the inside around exactly one
# first touch of a page, which is what `owns_window` is about and why what comes back has three
# frames at the top rather than the shell's own work.
#
# It is this recipe and not one of the writes because of the ordering on the page. The comparison
# above runs every recipe against its recording, and the two write recipes only match their
# recording on the first run of a boot: the second write to the same file finds the page already
# there and skips the part worth looking at. `page-fault` maps fresh memory every time, so it gives
# the same answer whether it has run before or not. That is recorded as `repeatable = true` in
# corpora/tier0/recipes.toml, with the measurement behind it, and `tests/test_web_programs.py`
# holds this file to naming a recipe that has it.
RECIPE = "page-fault"

tape = box.tape(
    RECIPE,
    do=lambda: box.sh("/bin/touchpage --quiet"),
    functions=("lock_mm_and_find_vma", "handle_mm_fault"),
    owns_window=True,
)

widget = SyscallTape(tape, max_depth=3, title="One page fault, traced in a browser tab")

json.dumps(
    {
        "kernel": box.read("/proc/version").strip(),
        "backend": box.describe(),
        "recipe": RECIPE,
        "frames": tape.frame_count,
        "roots": [root.name for root in tape.roots][:5],
        "root_count": len(tape.roots),
        "unparsed": len(tape.unparsed),
        "html": widget.html(),
        "text": widget.text(),
    }
)
