"""kxdraw, diagrams as code.

A diagram is a Python file. The `.svg` next to it is what the lesson shows, and the
`.excalidraw` next to that is what you open when you want to drag things around. Both are
generated by `just diagrams` and both are checked in CI, so a diagram cannot drift from its
source and nobody has to review a binary.
"""

from kxdraw.excalidraw import to_excalidraw
from kxdraw.scene import Arrow, Box, Note, Scene
from kxdraw.svg import to_svg

__all__ = ["Arrow", "Box", "Note", "Scene", "to_excalidraw", "to_svg"]
