"""Scenes: boxes, notes and arrows, with no rendering in them.

A diagram in this project is a short Python file, not a drawing. The Python file is the source of
truth and the `.excalidraw` and `.svg` beside it are output, regenerated by `just diagrams` and
checked in CI. Hand editing the output is the same mistake as hand editing a generated blueprint
section, so the check fails the build when somebody does it.

The reason is that a book with sixty diagrams in it has sixty diagrams that go stale. A diagram
you can grep, diff and review in a pull request is one somebody will actually fix.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# The palette. Four styles, on purpose. A diagram that needs a fifth colour is a diagram that is
# trying to say too much at once.
STYLES = {
    "plain": {"stroke": "#1e1e1e", "fill": "transparent"},
    "accent": {"stroke": "#1971c2", "fill": "#d0ebff"},
    "muted": {"stroke": "#868e96", "fill": "#f8f9fa"},
    "warn": {"stroke": "#e03131", "fill": "#ffe3e3"},
}

TEXT_COLOUR = "#1e1e1e"
MUTED_TEXT = "#5c5f66"
LINE_HEIGHT = 1.25

# Excalidraw's font ids. 1 is the hand drawn face, 3 is the monospace one.
FONT_HAND = 1
FONT_MONO = 3


@dataclass
class Box:
    key: str
    x: float
    y: float
    width: float
    height: float
    label: str = ""
    style: str = "plain"
    mono: bool = False
    font_size: float = 16.0
    dashed: bool = False

    @property
    def centre(self) -> tuple[float, float]:
        return (self.x + self.width / 2, self.y + self.height / 2)

    def port(self, side: str) -> tuple[float, float]:
        cx, cy = self.centre
        return {
            "top": (cx, self.y),
            "bottom": (cx, self.y + self.height),
            "left": (self.x, cy),
            "right": (self.x + self.width, cy),
        }[side]


@dataclass
class Note:
    key: str
    x: float
    y: float
    text: str
    font_size: float = 14.0
    mono: bool = False
    muted: bool = False
    align: str = "left"


@dataclass
class Arrow:
    key: str
    start: tuple[float, float]
    end: tuple[float, float]
    label: str | None = None
    dashed: bool = False


def facing_sides(a: Box, b: Box) -> tuple[str, str]:
    """Which side of each box an arrow between them should leave from.

    Whichever axis the two boxes are further apart on wins, which is what a person would do.
    """
    ax, ay = a.centre
    bx, by = b.centre
    if abs(bx - ax) > abs(by - ay):
        return ("right", "left") if bx > ax else ("left", "right")
    return ("bottom", "top") if by > ay else ("top", "bottom")


@dataclass
class Scene:
    title: str
    width: float = 960
    height: float = 600
    padding: float = 24
    elements: list[Box | Note | Arrow] = field(default_factory=list)
    _counter: int = 0

    def _key(self, kind: str) -> str:
        self._counter += 1
        return f"{kind}{self._counter:03d}"

    def box(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        label: str = "",
        *,
        style: str = "plain",
        mono: bool = False,
        font_size: float = 16.0,
        dashed: bool = False,
    ) -> Box:
        if style not in STYLES:
            raise ValueError(f"unknown style {style!r}, pick one of {sorted(STYLES)}")
        item = Box(self._key("box"), x, y, width, height, label, style, mono, font_size, dashed)
        self.elements.append(item)
        return item

    def note(
        self,
        x: float,
        y: float,
        text: str,
        *,
        font_size: float = 14.0,
        mono: bool = False,
        muted: bool = False,
        align: str = "left",
    ) -> Note:
        item = Note(self._key("note"), x, y, text, font_size, mono, muted, align)
        self.elements.append(item)
        return item

    def arrow(
        self,
        start: Box | tuple[float, float],
        end: Box | tuple[float, float],
        *,
        label: str | None = None,
        dashed: bool = False,
        sides: tuple[str, str] | None = None,
    ) -> Arrow:
        if isinstance(start, Box) and isinstance(end, Box):
            from_side, to_side = sides or facing_sides(start, end)
            a, b = start.port(from_side), end.port(to_side)
        else:
            a = start.centre if isinstance(start, Box) else start
            b = end.centre if isinstance(end, Box) else end
        item = Arrow(self._key("arrow"), a, b, label, dashed)
        self.elements.append(item)
        return item

    @property
    def boxes(self) -> list[Box]:
        return [e for e in self.elements if isinstance(e, Box)]

    @property
    def arrows(self) -> list[Arrow]:
        return [e for e in self.elements if isinstance(e, Arrow)]

    @property
    def notes(self) -> list[Note]:
        return [e for e in self.elements if isinstance(e, Note)]
